### ISSUE TITLE
Running with custom lyrics?

### ISSUE THREAD

**Issue by georgezywang** [SwagLyrics/autosynch#64]
First and foremost, thank you for posting this project!
I am trying to utilize this program on one of my projects. It seems that there is an external API handling the lyrics, namely `from swaglyrics.cli import get_lyrics` in `align.py`. I wonder is there an option to supply my own lyrics? If not, what is the format of lyrics that get_lyrics returns? Thanks in advance!

**Comment by aadibajpai** [comment]
> First and foremost, thank you for posting this project!
> I am trying to utilize this program on one of my projects. It seems that there is an external API handling the lyrics, namely `from swaglyrics.cli import get_lyrics` in `align.py`. I wonder is there an option to supply my own lyrics? If not, what is the format of lyrics that get_lyrics returns? Thanks in advance!

Hey! Thanks for your interest in the project. `get_lyrics` returns the lyrics from Genius so that's the format, you can check out the source at https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/swaglyrics/cli.py#L64. 

You can definitely pass custom lyrics to it where `get_lyrics` is used, but it might just be easier to continue with the Genius ones since autosynch was written with those in mind so we don't know how custom ones will fare. Probably should be okay but who knows.

**Comment by georgezywang** [comment]
> > First and foremost, thank you for posting this project!
> > I am trying to utilize this program on one of my projects. It seems that there is an external API handling the lyrics, namely `from swaglyrics.cli import get_lyrics` in `align.py`. I wonder is there an option to supply my own lyrics? If not, what is the format of lyrics that get_lyrics returns? Thanks in advance!
> 
> Hey! Thanks for your interest in the project. `get_lyrics` returns the lyrics from Genius so that's the format, you can check out the source at https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/swaglyrics/cli.py#L64.
> 
> You can definitely pass custom lyrics to it where `get_lyrics` is used, but it might just be easier to continue with the Genius ones since autosynch was written with those in mind so we don't know how custom ones will fare. Probably should be okay but who knows.

Thank you for your quick reply! The source code is very helpful. I ran into a `KeyError: 'default'` issue yesterday and thought it might be due to the implementation of `get_lyrics`. Turns out it is very well written. The issue seems to be in autosynch. There seems to be a minor issue in `align.py` which if a song has no chorus at all 

`gt_chorus_syl = mean(section[1]/gt_max_syl for section in sc_syllables if section[0] == 'chorus')` 

will raise an error since python is not able to take mean over 0 data points. Another issue I encountered is that if a song has no labels (like this one https://genius.com/Jayn-smoke-and-mirrors-lyrics), i.e. get_lyrics will return the key `default` for all sections, the dp implementation 

`dp[i][j] = dp_err_matrix[sc_syllables[i][0]][relabels[j]]`

will raise an error since `dp_err_matrix` does not include a `default` key. Not sure if I am missing something here, but I guess that is not a very common issue since Genius has most songs labeled. I am able to get the code working now, just thought you may be interested in those weird issues (I was trying to make NightCore music so the songs I used are mostly not the popular ones). But again, thank you for posting this :)

**Comment by aadibajpai** [comment]
> > > First and foremost, thank you for posting this project!
> > > I am trying to utilize this program on one of my projects. It seems that there is an external API handling the lyrics, namely `from swaglyrics.cli import get_lyrics` in `align.py`. I wonder is there an option to supply my own lyrics? If not, what is the format of lyrics that get_lyrics returns? Thanks in advance!
> > 
> > 
> > Hey! Thanks for your interest in the project. `get_lyrics` returns the lyrics from Genius so that's the format, you can check out the source at https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/swaglyrics/cli.py#L64.
> > You can definitely pass custom lyrics to it where `get_lyrics` is used, but it might just be easier to continue with the Genius ones since autosynch was written with those in mind so we don't know how custom ones will fare. Probably should be okay but who knows.
> 
> Thank you for your quick reply! The source code is very helpful. I ran into a `KeyError: 'default'` issue yesterday and thought it might be due to the implementation of `get_lyrics`. Turns out it is very well written. The issue seems to be in autosynch. There seems to be a minor issue in `align.py` which if a song has no chorus at all
> 
> `gt_chorus_syl = mean(section[1]/gt_max_syl for section in sc_syllables if section[0] == 'chorus')`
> 
> will raise an error since python is not able to take mean over 0 data points. Another issue I encountered is that if a song has no labels (like this one https://genius.com/Jayn-smoke-and-mirrors-lyrics), i.e. get_lyrics will return the key `default` for all sections, the dp implementation
> 
> `dp[i][j] = dp_err_matrix[sc_syllables[i][0]][relabels[j]]`
> 
> will raise an error since `dp_err_matrix` does not include a `default` key. Not sure if I am missing something here, but I guess that is not a very common issue since Genius has most songs labeled. I am able to get the code working now, just thought you may be interested in those weird issues (I was trying to make NightCore music so the songs I used are mostly not the popular ones). But again, thank you for posting this :)

thanks! that's helpful to know and we should probably check those out, @chriswang030 if you remember whether we encountered something similar maybe.

meanwhile, I'll close this issue but feel free to reach out in case something else comes up!
